zanata/zanata-server

- zanata-war/src/main/java/org/zanata/action/LanguageManagerAction.java
https://bugzilla.redhat.com/show_bug.cgi?id=1180988
> fix adding arbitrary language in zanata

- functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java
- functional-test/src/main/java/org/zanata/page/administration/ManageLanguagePage.java
- functional-test/src/test/java/org/zanata/feature/language/AddLanguageTest.java
Also pause a moment for plurals warning.
> Fix broken logic of test add/manage language pages

- functional-test/src/main/java/org/zanata/page/AbstractPage.java
- functional-test/src/main/java/org/zanata/page/projectversion/VersionBasePage.java
- functional-test/src/main/java/org/zanata/page/projectversion/VersionDocumentsPage.java
Remove superfluous waits
Wait for the project version settings page to exist before moving to it
Add logging as to exactly what the system is waiting for
> Wait for settings tab, be less wait-ish in waiting for it

- functional-test/src/main/java/org/zanata/page/CorePage.java
- functional-test/src/main/java/org/zanata/page/account/EditProfilePage.java
- functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
- functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectGeneralTab.java
- functional-test/src/main/java/org/zanata/page/projectversion/CreateVersionPage.java
- functional-test/src/test/java/org/zanata/feature/account/RegisterTest.java
- functional-test/src/test/java/org/zanata/feature/account/UsernameValidationTest.java
- functional-test/src/test/java/org/zanata/feature/projectversion/CreateProjectVersionTest.java
In some cases, element.blur works more reliably than a page click
> Fix test element focus issues

- zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
- zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
- zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java
- zanata-war/src/main/java/org/zanata/config/DatabaseBackedConfig.java
- zanata-war/src/test/java/org/zanata/config/DatabaseBackedConfigTest.java
Remove reference of helpContent from application.
Post cleanup from https://bugzilla.redhat.com/show_bug.cgi?id=1195384
> Remove reference of helpContent

- functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectLanguagesTab.java
- functional-test/src/main/java/org/zanata/page/projectversion/versionsettings/VersionLanguagesTab.java
- functional-test/src/main/java/org/zanata/util/LanguageList.java
- functional-test/src/test/java/org/zanata/feature/language/AddLanguageTest.java
- functional-test/src/test/java/org/zanata/feature/project/EditProjectAboutTest.java
- functional-test/src/test/java/org/zanata/feature/project/EditProjectLanguagesTest.java
- functional-test/src/test/java/org/zanata/feature/projectversion/EditVersionLanguagesTest.java
Significant changes to language add/remove behaviour in projects.
Moves the test page behaviour to a utility class, as it is shared in
project and version settings.
> Fix language tests

- functional-test/src/test/java/org/zanata/feature/project/EditProjectValidationsTest.java
- functional-test/src/test/java/org/zanata/feature/projectversion/EditVersionValidationsTest.java
> Skip some notifications which have regressed

- functional-test/src/main/java/org/zanata/page/administration/ServerConfigurationPage.java
- functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
- zanata-war/src/main/webapp/admin/server_configuration.xhtml
Also adds a "purge" function to the HasEmailRule feature.
> Administration page settings tests

- zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
- zanata-war/src/main/java/org/zanata/notification/LanguageTeamPermissionChangeJmsMessagePayloadHandler.java
- zanata-war/src/main/java/org/zanata/security/AuthenticationManager.java
- zanata-war/src/main/resources/messages.properties
https://bugzilla.redhat.com/show_bug.cgi?id=1201080
> Fix servr url bug

- docs/release-notes.md
- zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
- zanata-war/src/main/java/org/zanata/async/AsyncTaskManager.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
- zanata-war/src/test/resources/arquillian/persistence.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1197902
> rhbz1197902 - clear hibernate session after each translation batch save

- zanata-war/src/main/webapp/WEB-INF/layout/language/language_view.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1205465
> display email only to admin in language page

- zanata-war/src/main/java/org/zanata/action/SupportedLanguageAction.java
- zanata-war/src/main/webapp/language/home.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1205468
> Fix language sorting in members size

- zanata-war/pom.xml
https://bugzilla.redhat.com/show_bug.cgi?id=875965
> Update assets version to 6.1 for whitespace changes

- docs/release-notes.md
- pom.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1029734
> upgrade zanata-common to 3.6.0

- zanata-war/src/main/java/org/zanata/action/ProjectHome.java
Left this in by mistake, and @carlosmunoz noticed that it is generating a bunch of noise in the log.
> Remove log message that was unintentionally committed

- zanata-war/src/main/resources/pluralforms.properties
Plural information from the user:
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
> add plural form for me-ME

- functional-test/src/test/resources/conf/standalone.xml
- functional-test/src/test/resources/conf/standalone_wildfly.xml
- zanata-overlay/distros/eap-6/standalone/configuration/standalone-zanata.xml
- zanata-overlay/distros/wildfly-8.1/standalone/configuration/standalone-zanata.xml
- zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
- zanata-war/src/test/resources/arquillian/standalone-arquillian.xml
https://access.redhat.com/solutions/309913
> Prevent connection leaks

- functional-test/pom.xml
- pom.xml
- zanata-war/pom.xml
Replaces https://github.com/zanata/zanata-server/pull/763
> Separate wildfly client version from server version

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/DocumentListPresenter.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/ValidationOptionsView.java
when there is no validation to run
https://bugzilla.redhat.com/show_bug.cgi?id=1205512
> rhbz1205512 - run validation button on document list page wont be disabled

- functional-test/src/main/java/org/zanata/page/AbstractPage.java
- functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
- functional-test/src/test/java/org/zanata/feature/testharness/ZanataTestCase.java
Two commits - cherry pick the excessive waits commit and extend the short/long test timeouts to 3min/10min respectively.
> Time extension

- docs/release-notes.md
- pom.xml
- zanata-liquibase/pom.xml
- zanata-liquibase/src/main/java/liquibase/ext/CreateTableGeneratorInnoDB.java
- zanata-liquibase/src/main/java/liquibase/ext/MySQLDatabaseWithLog.java
- zanata-war/pom.xml
- zanata-war/src/main/resources/db/changelogs/db.changelog-1.0.xml
- zanata-war/src/main/resources/db/changelogs/db.changelog-3.6.xml
- zanata-war/src/main/resources/db/changelogs/db.changelog-3.7.xml
- zanata-war/src/main/resources/db/changelogs/db.changelog-validations.xml
- zanata-war/src/main/resources/db/db.changelog.xml
Forward port of https://github.com/zanata/zanata-server/pull/773
> Ensure innodb on 3.7

- docs/user-guide/documents/custom-document-param.md
- docs/user-guide/documents/download-translated-documents.md
- docs/user-guide/documents/raw-documents.md
- docs/user-guide/documents/upload-documents.md
- docs/user-guide/project-maintainer-guide.md
- docs/user-guide/projects/gettext-example.md
- docs/user-guide/projects/podir-example.md
- docs/user-guide/system-admin/configuration/installation.md
- mkdocs.yml
Moved pages from 
https://github.com/zanata/zanata-server/wiki/Raw-Documents and https://github.com/zanata/zanata-server/wiki/Features to readthedocs.
> Add raw documents documentation

- zanata-war/src/main/java/org/zanata/action/ContactAdminAction.java
- zanata-war/src/main/java/org/zanata/action/LanguageContactCoordinatorAction.java
- zanata-war/src/main/java/org/zanata/action/LanguageJoinAction.java
- zanata-war/src/main/java/org/zanata/action/PasswordResetRequestAction.java
- zanata-war/src/main/java/org/zanata/action/VersionGroupJoinAction.java
- zanata-war/src/main/java/org/zanata/dao/AccountDAO.java
- zanata-war/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/resources/org/zanata/email/templates/email_admin_anonymous.vm
- zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal_anonymous.xhtml
- zanata-war/src/main/webapp/WEB-INF/urlrewrite.xml
- zanata-war/src/main/webapp/account/google_password_reset_request.xhtml
- zanata-war/src/main/webapp/account/login.xhtml
- zanata-war/src/main/webapp/account/password_reset_request.xhtml
- zanata-war/src/main/webapp/account/register.xhtml
Remove google open id from signup page, redirect google login to password reset page, allow anonymous user to contact admin from google reset password page.
https://bugzilla.redhat.com/show_bug.cgi?id=1218002
> Remove google open id from signup page

- docs/release-notes.md
https://bugzilla.redhat.com/show_bug.cgi?id=1218002
> Add release notes for https://github.com/zanata/zanata-server/pull/800

- zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml
See also https://github.com/zanata/zanata-server/pull/721
> Declare required resources in jboss-web.xml

- pom.xml
- zanata-war/src/test/java/org/zanata/service/impl/CopyTransServiceImplPerformanceTest.java
https://bugzilla.redhat.com/show_bug.cgi?id=1207994
> Update Liquibase to 3.3.3

- functional-test/src/main/java/org/zanata/page/CorePage.java
> Re-enable critical error check on page load

- zanata-war/src/main/java/org/eclipse/jetty/server/handler/AbstractHandler.java
https://liquibase.jira.com/browse/CORE-2024
> Add workaround for Liquibase CORE-2024

- functional-test/pom.xml
Latest Firefox does not work with versions previous
> Bump Selenium version to 2.45

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/AppPresenter.java
https://bugzilla.redhat.com/show_bug.cgi?id=1223597
> Fix null pointer exception for large document list in editor

- docs/release-notes.md
- zanata-war/src/main/webapp/WEB-INF/layout/version/edit_form.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1165930
> Hide copy from previous version with only obsolete version

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/java/org/zanata/webtrans/server/rpc/GetDocumentListHandler.java
https://bugzilla.redhat.com/show_bug.cgi?id=1098362
> Encode docId for download action in webtrans

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/java/org/zanata/webtrans/client/history/Token.java
- zanata-war/src/main/java/org/zanata/webtrans/shared/util/TokenUtil.java
- zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1225689
> Fix non-encoded doc id in view

- functional-test/src/main/java/org/zanata/page/projectversion/VersionBasePage.java
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
Disable require review option until https://bugzilla.redhat.com/show_bug.cgi?id=1211137 is implemented.
> Disable require review option

- pom.xml
http://blog.liquibase.org/2015/05/liquibase-3-3-4-released.html
> Upgrade to Liquibase 3.3.4

- docs/release-notes.md
- functional-test/src/test/java/org/zanata/feature/account/RegisterTest.java
- zanata-war/src/main/java/org/zanata/action/RegisterAction.java
https://bugzilla.redhat.com/show_bug.cgi?id=981498
> Update username regular expression

- docs/release-notes.md
- zanata-war/src/main/webapp/resources/zanata/autocomplete.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1224030
> bind cut and paste event for autocomplete input field

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/ProjectSearch.java
- zanata-war/src/main/java/org/zanata/dao/AccountDAO.java
https://bugzilla.redhat.com/show_bug.cgi?id=1227575
> Limit user search result

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/LanguageAction.java
- zanata-war/src/main/webapp/WEB-INF/pages.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1198898
> Redirect to language list page if language is not supported

- docs/release-notes.md
- zanata-war/src/main/resources/ValidationMessages.properties
https://bugzilla.redhat.com/show_bug.cgi?id=1116172
Most of the captcha implementation is removed in https://bugzilla.redhat.com/show_bug.cgi?id=1191321
> Remove unused captcha message

- pom.xml
Got 8 functional test failures in a branch with this. Trying it independently to see whether the tests pass.
> Update api and common

- docs/release-notes.md
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/admin/stats.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1230424
> Update 'archived' to 'deleted' in activity table

- frontend/src/main/web/user-profile-page/package.json
- frontend/src/main/web/user-profile-page/webpack.prod.config.js
also configure it to fail the build if something wrong
> fix webpack version to the one works before

- frontend/README.md
- frontend/pom.xml
- frontend/src/main/web/user-profile-page/npm-shrinkwrap.json
- frontend/src/main/web/user-profile-page/package.json
- frontend/src/main/web/user-profile-page/webpack.prod.config.js
There is a build problem with webpack 1.9.11. I submitted an issue and got back the answer:
https://github.com/webpack/webpack/issues/1168#issuecomment-111968406
Also ran shrinkwrap to fix the npm modules so we won't have issues like this anymore (repeatable build)
> shrinkwrap npm modules and fix webpack build problem

- zanata-war/src/main/java/org/zanata/webtrans/shared/validation/action/JavaVariablesValidation.java
- zanata-war/src/test/java/org/zanata/service/impl/TranslationFinderTest.java
- zanata-war/src/test/java/org/zanata/webtrans/shared/validation/JavaVariablesValidationTest.java
1. Fix JVM 1.8 incompatibility
2. Reduce unnecessary test executions
> Fix tests on JVM 1.8; reduce executions

- pom.xml
- zanata-war/pom.xml
> Update zanata-maven-plugin version to zanta-client-version

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/ui/ActivityEntry.java
https://bugzilla.redhat.com/show_bug.cgi?id=1231054
> Fix null exception in more activity load

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/file/SourceDocumentUpload.java
fileType in uploadForm is now DocumentType.
https://zanata.atlassian.net/browse/ZANATA-8
> ZANATA-8 fix error uploading pot file from web UI

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java
https://bugzilla.redhat.com/show_bug.cgi?id=1235495
> rhbz1235495,ZANATA-20 - fix error in uploading po file from web UI

- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-general.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/project/validation-settings-block.xhtml
This just moves the content from 2 of the settings tabs to separate files. No template code should be any different.
> Refactor project settings

- zanata-war/src/main/java/org/zanata/rest/ZanataRestResponseInterceptor.java
> CORS Support

- zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/Breadcrumb.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/Breadcrumb.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TMMergeForm.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TMMergeForm.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TooltipPopupPanel.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TooltipPopupPanel.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TransUnitCountBar.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransFilterView.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransUnitNavigationView.ui.xml
Update editor color to use assets.
> Update editor color

- functional-test/src/main/java/org/zanata/page/dashboard/dashboardsettings/DashboardClientTab.java
- functional-test/src/test/java/org/zanata/feature/language/JoinLanguageTeamTest.java
- functional-test/src/test/java/org/zanata/util/HasEmailRule.java
It appears that there was a race condition with the alert disappearing
and the number of expected background functions.
> Fix ProfileTest generate api key test

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/VersionHome.java
- zanata-war/src/main/webapp/WEB-INF/layout/project/versions-tab.xhtml
https://bugzilla.redhat.com/show_bug.cgi?id=1242679
> fix(copy version): refresh version entry in UI after copy version

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/VersionGroupHome.java
- zanata-war/src/main/java/org/zanata/action/VersionGroupHomeAction.java
- zanata-war/src/main/java/org/zanata/action/ZanataSearch.java
- zanata-war/src/main/java/org/zanata/util/ComparatorUtil.java
- zanata-war/src/main/webapp/WEB-INF/layout/search/projects-tab.xhtml
- zanata-war/src/test/java/org/zanata/util/ComparatorUtilTest.java
https://bugzilla.redhat.com/show_bug.cgi?id=1243251
> fix(search): Fix sort in Zanata search page

- zanata-war/src/test/java/org/zanata/service/impl/DocumentServiceImplTest.java
https://github.com/zanata/zanata-server/commit/bd33f08c933c8572725d0d8f131cd654aaee5b50#commitcomment-12215913
> fix,test(Functional test): fix broken functional test

- etc/scripts/extractAppserver.groovy
- functional-test/pom.xml
- pom.xml
- zanata-war/pom.xml
- zanata-war/src/etc/dependencyVersions.groovy
Simple cherry-pick of https://github.com/zanata/zanata-server/pull/864
> Backport "Simplify appserver properties"

- docs/user-guide/projects/project-settings.md
- zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml
Fix from bug found in demo, 
- update documentation
- add permission check in create-project button in dashboard
> fix(create-project): update docs, add permission check for create project

- zanata-war/src/main/java/org/zanata/ZanataInit.java
https://bugzilla.redhat.com/show_bug.cgi?id=1244612
> fix(search): rhbz1244612 close EntityManagerFactory at shutdown

- zanata-war/src/main/java/org/zanata/dao/ActivityDAO.java
https://zanata.atlassian.net/browse/ZNTA-35
> fix(activity): Update activity query to improve performance

- pom.xml
Point zanata dependency to the one that in integration/master
> chore(dependency): update version for server-3.8.0

- zanata-war/src/main/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandler.java
- zanata-war/src/test/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandlerTest.java
https://zanata.atlassian.net/browse/ZNTA-615
> fix(glossary): Fix glossary permission

- zanata-war/src/main/java/org/zanata/action/VersionHome.java
https://zanata.atlassian.net/browse/ZNTA-643
> fix(version language): Fix concurrent map modification

- zanata-war/pom.xml
https://zanata.atlassian.net/browse/ZNTA-638
> fix(ZNTA-638): upgrade ehcache

- zanata-war/src/main/java/org/zanata/log4j/ZanataHTMLLayout.java
- zanata-war/src/main/java/org/zanata/log4j/package-info.java
- zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java
https://zanata.atlassian.net/browse/ZNTA-653
See also https://github.com/zanata/zanata-server/pull/951 to get username logging working again.
> feat(logging): include MDC values in log emails

- pom.xml
- zanata-war/src/main/java/org/zanata/log4j/ZanataHTMLLayout.java
- zanata-war/src/main/java/org/zanata/log4j/package-info.java
- zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java
(cherry picked from commit 4a4793da7b8603c331e161fdf0b7ae0661e23897) https://github.com/zanata/zanata-server/pull/946
> BACKPORT feat(logging): include MDC values and time in emails

- pom.xml
- zanata-war/src/main/resources/db/changelogs/db.changelog-3.7.xml
(cherry picked from commit 6ac8d8a3b9172166d4c96416c6bc79f6be0d1f23)
See also https://github.com/zanata/zanata-server/pull/952
> BACKPORT perf(liquibase): merge addColumn changes

- zanata-war/src/main/java/org/zanata/action/DataPage.java
- zanata-war/src/main/java/org/zanata/action/PagedListDataModel.java
- zanata-war/src/main/java/org/zanata/action/ProjectPagedListDataModel.java
- zanata-war/src/main/java/org/zanata/dao/ProjectDAO.java
https://zanata.atlassian.net/browse/ZNTA-637
> fix(ZNTA-637): improve error messages

- docs/user-guide/account/account-settings.md
- docs/user-guide/client/client.md
- docs/user-guide/documents/download-translated-documents.md
- docs/user-guide/documents/upload-documents.md
- docs/user-guide/glossary/delete-glossaries.md
- docs/user-guide/glossary/upload-glossaries.md
- docs/user-guide/project-maintainer-guide.md
- docs/user-guide/projects/create-project.md
- docs/user-guide/projects/gettext-example.md
- docs/user-guide/projects/import-projects.md
- docs/user-guide/projects/podir-example.md
- docs/user-guide/projects/project-types.md
- docs/user-guide/versions/create-version.md
Also fix broken links to old Installation page
> Change client doc links to use docs.zanata.org

- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TransFilterPresenter.java
https://zanata.atlassian.net/browse/ZNTA-686
> ZNTA-686 fix(editor) - fix date validator pattern

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/rest/editor/service/UserService.java
https://zanata.atlassian.net/browse/ZNTA-696
> Fix required false for authenticated user

- docs/release-notes.md
- zanata-war/src/main/webapp/account/login.xhtml
https://zanata.atlassian.net/browse/ZNTA-9
> Fix account activation message not display

- zanata-model/src/main/java/org/zanata/model/HProject.java
- zanata-war/src/main/java/org/zanata/action/CopyTransAction.java
- zanata-war/src/main/java/org/zanata/action/LocaleSelectorAction.java
- zanata-war/src/main/java/org/zanata/action/MergeTransAction.java
- zanata-war/src/main/java/org/zanata/action/ProfileAction.java
- zanata-war/src/main/java/org/zanata/action/ProfileHome.java
- zanata-war/src/main/java/org/zanata/action/RoleSearch.java
- zanata-war/src/main/java/org/zanata/action/UserAction.java
- zanata-war/src/main/java/org/zanata/action/UserSearch.java
- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/java/org/zanata/dao/AccountDAO.java
- zanata-war/src/main/java/org/zanata/events/LocaleSelectedEvent.java
- zanata-war/src/main/java/org/zanata/i18n/Messages.java
- zanata-war/src/main/java/org/zanata/rest/service/ResourceUtils.java
- zanata-war/src/main/java/org/zanata/util/PasswordUtil.java
- zanata-war/src/main/webapp/WEB-INF/pages.xml
- zanata-war/src/main/webapp/WEB-INF/template/footer.xhtml
- zanata-war/src/main/webapp/admin/rolemanager.xhtml
- zanata-war/src/test/java/org/zanata/util/PasswordUtilTest.java
> refactor - remove various Seam references

- functional-test/pom.xml
See https://zanata.atlassian.net/browse/ZNTA-707
> chore: add option to test against lowercase mysql

- functional-test/src/test/resources/conf/standalone.xml
See also https://github.com/zanata/zanata-server/pull/1003
> test: bind EAP to localhost only

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/MergeTransAction.java
- zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java
https://zanata.atlassian.net/browse/ZNTA-718
> fix(merge translation):allow admin/maintainer to merge from all active projects

- functional-test/src/main/java/org/zanata/page/groups/CreateVersionGroupPage.java
- functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java
- functional-test/src/main/java/org/zanata/page/projects/CreateProjectPage.java
- functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectGeneralTab.java
- functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectPermissionsTab.java
- functional-test/src/main/java/org/zanata/page/projectversion/CreateVersionPage.java
Return this is page functions bypasses the AbstractPage waits/checks.
> fix(test): Replace return this with return new Page

- zanata-war/src/main/webapp-jboss/WEB-INF/jboss-deployment-structure.xml
This helps with WildFly 10 compatibility.
> Exclude Hibernate Search module

- zanata-war/src/main/webapp/WEB-INF/layout/version-group/languages-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version-group/projects-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/template/footer.xhtml
- zanata-war/src/main/webapp/WEB-INF/template/template.xhtml
- zanata-war/src/main/webapp/iteration/view.xhtml
- zanata-war/src/main/webapp/resources/zanata/list-filter.xhtml
- zanata-war/src/main/webapp/resources/zanata/loader.xhtml
- zanata-war/src/main/webapp/version-group/version_group.xhtml
The other part of the fix is in zanata-assets:
https://github.com/zanata/zanata-assets/commit/7079cddc066216c3e28ea977322e566bf98c5ddc
> adjust markup and function calls for scrollable panels

- zanata-war/src/main/java/org/zanata/ZanataInit.java
- zanata-war/src/main/webapp-jboss/WEB-INF/classes/META-INF/persistence.xml
- zanata-war/src/test/resources/META-INF/persistence.xml
- zanata-war/src/test/resources/arquillian/persistence.xml
Partly reverts https://github.com/zanata/zanata-server/pull/562
> Use native Lucene locks for NFS safety

- pom.xml
https://zanata.atlassian.net/browse/ZNTA-705
> Upgrade to Liquibase 3.4.1

- zanata-overlay/common/bin/zanata-installer/InstallZanata.groovy
Ask for confirmation before downloading zanata.war
Download war from github instead of sourceforge
> chore(installer): minor changes to the installer script

- frontend/src/main/web/lib/components/glossary/DataTable.jsx
- frontend/src/main/web/lib/components/glossary/InputCell.jsx
- frontend/src/main/web/lib/components/glossary/NewEntryModal.jsx
- zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-755
https://zanata.atlassian.net/browse/ZNTA-753
> fix(glossary): limit glossary input field

- frontend/src/main/web/lib/components/SystemGlossary.jsx
- frontend/src/main/web/lib/components/glossary/DataTable.jsx
- frontend/src/main/web/lib/stores/GlossaryStore.js
- zanata-war/src/main/java/org/zanata/action/GlossaryAction.java
https://zanata.atlassian.net/browse/ZNTA-757
> fix(glossary):hide delete button for non-glossary admin user

- frontend/src/main/web/lib/components/glossary/ImportModal.jsx
https://zanata.atlassian.net/browse/ZNTA-756
> fix(glossary): show not supported file message

- zanata-war/src/main/webapp/WEB-INF/layout/search/projects-tab.xhtml
https://zanata.atlassian.net/browse/ZNTA-775
> fix(search page icon): update project icon in search page

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/ActivateAction.java
- zanata-war/src/main/webapp/account/activate.xhtml
https://zanata.atlassian.net/browse/ZNTA-720
> fix(activate account): redirect to login page after account activate

- zanata-war/src/main/java/org/zanata/rest/editor/service/UserService.java
- zanata-war/src/main/webapp/profile/home.xhtml
https://zanata.atlassian.net/browse/ZNTA-774
> fix(user-profile): fix user profile page display

- zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-738
> fix(revert translation): fix null pointer exception when revert translation

- frontend/src/main/web/lib/components/glossary/ImportModal.jsx
- frontend/src/main/web/lib/stores/GlossaryAPIStore.js
- pom.xml
- zanata-war/src/main/java/org/zanata/service/GlossaryFileService.java
- zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java
- zanata-war/src/test/java/org/zanata/service/impl/GlossaryFileServiceImplTest.java
https://zanata.atlassian.net/browse/ZNTA-778
> fix(glossary):Add utf8 for glossary po file upload

- functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
- zanata-war/src/main/java/org/zanata/action/ActivateAction.java
- zanata-war/src/main/webapp/account/activate.xhtml
Display activation message after redirect
https://zanata.atlassian.net/browse/ZNTA-720
> fix(activation): display activation message

- docs/release-notes.md
- zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
- zanata-war/src/main/webapp/dashboard/home.xhtml
- zanata-war/src/main/webapp/iteration/view.xhtml
- zanata-war/src/main/webapp/resources/script/components-script.js
https://zanata.atlassian.net/browse/ZNTA-767
> fix(url):handle whitespace and slash in doc id url

- zanata-war/src/main/webapp-jboss/WEB-INF/web.xml
- zanata-war/src/main/webapp/admin/monitoring.xhtml
https://zanata.atlassian.net/browse/ZNTA-803
> fix(ZNTA-803): Fix broken link to admin monitoring page

- zanata-war/pom.xml
There rae duplicate cdi-unit dependency items.
> chore(dependency): remove duplicate cdi-unit

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/email/EmailBuilder.java
- zanata-war/src/test/java/org/zanata/email/EmailStrategyTest.java
https://zanata.atlassian.net/browse/ZNTA-804
> fix(email): bcc for all email recipient

- functional-test/src/main/java/org/zanata/page/dashboard/dashboardsettings/DashboardAccountTab.java
- functional-test/src/test/java/org/zanata/feature/account/ChangePasswordTest.java
- zanata-war/src/main/java/org/zanata/action/PasswordResetAction.java
- zanata-war/src/main/java/org/zanata/action/UserSettingsAction.java
- zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml
Fix missing password length changes from PR #989
> Increase other password lengths to 1024

- pom.xml
http://www.liquibase.org/2015/11/liquibase-3-4-2-released.html
> Upgrade to liquibase 3.4.2

- pom.xml
- zanata-war/src/main/java/org/zanata/action/ActivateAction.java
- zanata-war/src/main/java/org/zanata/security/UserRedirectBean.java
- zanata-war/src/main/webapp/account/activate.xhtml
https://zanata.atlassian.net/browse/ZNTA-815
Due to bug in jsf 2.1, we are unable to display activation message in the login screen after redirection. This will be solve in the CDO branch.
> fix(login redirect):prevent login page redirection after activate account

- docs/release-notes.md
- pom.xml
https://zanata.atlassian.net/browse/ZNTA-812
> fix(Project search&replace):fix bad encoding in search text

- pom.xml
- zanata-war/src/main/webapp/WEB-INF/layout/version/merge_trans_modal.xhtml
https://zanata.atlassian.net/browse/ZNTA-844
> fix(merge trans dialog):update broken dialog for merge trans

- docs/release-notes.md
- frontend/src/main/web/lib/components/glossary/DataTable.jsx
- zanata-war/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java
https://zanata.atlassian.net/browse/ZNTA-854
> fix(glossary): prevent load of description for undefined term

- zanata-war/src/main/java/org/zanata/dao/ApplicationConfigurationDAO.java
https://zanata.atlassian.net/browse/ZNTA-882
> fix(applicationConfig): update dao scope to RequestScope

- zanata-war/src/main/java/org/zanata/action/PasswordResetAction.java
- zanata-war/src/main/java/org/zanata/action/PasswordResetRequestAction.java
- zanata-war/src/main/java/org/zanata/dao/AccountResetPasswordKeyDAO.java
- zanata-war/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-870
> fix(password reset): fix entry not inserted into db

- zanata-war/src/main/java/org/zanata/action/UserAction.java
https://zanata.atlassian.net/browse/ZNTA-886
> fix(account enable): remove activation key entry when account enable by admin

- zanata-war/src/main/java/org/zanata/security/openid/FedoraOpenIdProvider.java
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
> Update Fedora OpenID endpoint to secure one

- docs/release-notes.md
- frontend/src/main/web/lib/components/UserProfile.jsx
- zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
- zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
- zanata-war/src/main/java/org/zanata/action/ProfileHome.java
- zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java
- zanata-war/src/main/java/org/zanata/config/DatabaseBackedConfig.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/UserService.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java
- zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml
- zanata-war/src/main/webapp/admin/server_configuration.xhtml
- zanata-war/src/main/webapp/resources/zanata/maintainers-tab.xhtml
- zanata-war/src/test/java/org/zanata/rest/editor/service/UserServiceTest.java
- zanata-war/src/test/java/org/zanata/rest/service/ProjectVersionServiceUnitTest.java
https://zanata.atlassian.net/browse/ZNTA-879
API
- project contributors list - when configuration for display user set to true
- user service (private api for editor, /user/{username}) -  when configuration for display user set to true
UI
- user profile page - when logged in and configuration for display user set to true
> feat(user email): admin can configure to display user email

- docs/release-notes.md
https://zanata.atlassian.net/browse/ZNTA-801
> ZNTA-801 Add release notes for CDI (enable Weld)

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-905
> fix(translation memory): remove 0% matching TM entry

- pom.xml
- zanata-war/src/test/java/org/zanata/rest/compat/CompatibilityBase.java
- zanata-war/src/test/java/org/zanata/rest/compat/StatisticsCompatibilityITCase.java
- zanata-war/src/test/java/org/zanata/rest/service/raw/ResourceServiceRestITCase.java
depends on https://github.com/zanata/zanata-api/pull/41
> Znta 519 - allow -_. in document name

- docs/release-notes.md
- functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java
- zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml
- zanata-war/src/main/webapp/resources/zanata/maintainers-tab.xhtml
- zanata-war/src/main/webapp/resources/zanata/person-tile.xhtml
https://zanata.atlassian.net/browse/ZNTA-412
> fix(user): profile link to user page

- functional-test/src/main/java/org/zanata/page/AbstractPage.java
- functional-test/src/main/java/org/zanata/page/administration/ServerConfigurationPage.java
- functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java
- functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
- functional-test/src/test/java/org/zanata/feature/testharness/TestPlan.java
> fix(ZNTA-668): Server settings tests disabled

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/TranslationMemoryAction.java
https://zanata.atlassian.net/browse/ZNTA-793
> fix(tm action): fix TranslationMemoryAction.lastTaskResult

- docs/release-notes.md
- zanata-war/src/main/webapp/WEB-INF/layout/project/languages-list.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
https://zanata.atlassian.net/browse/ZNTA-953
> fix(version): delete version

- pom.xml
- zanata-model/pom.xml
- zanata-war/pom.xml
Update xom:xom to com.io7m.xom
See also:
https://github.com/zanata/zanata-parent/pull/52
https://github.com/zanata/zanata-common/pull/20
> chore(dependency): Update dependencies to what Fedora 23 has

- zanata-war/src/main/webapp-jboss/WEB-INF/jboss-deployment-structure.xml
Partially reverts 83c855871ccc5ea9c5cf67385fe61acd6459e5d7.
> Fix ClassCastException on WildFly

- functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectLanguagesTab.java
- functional-test/src/main/java/org/zanata/page/projectversion/versionsettings/VersionLanguagesTab.java
- functional-test/src/main/java/org/zanata/util/LanguageList.java
- functional-test/src/test/java/org/zanata/feature/project/EditProjectLanguagesTest.java
- functional-test/src/test/java/org/zanata/feature/projectversion/EditVersionLanguagesTest.java
- zanata-war/src/main/webapp/WEB-INF/layout/project/languages-list.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-languages.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab-languages.xhtml
Also add some tests for locale filtering.
> Fix SyntaxError on WildFly

- pom.xml
Need from building with  -Prelease and zanata-parent-25
> chore(profile): disable doclint for Java 8 when building with release

- zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
- zanata-war/src/main/java/org/zanata/service/TranslationMergeService.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationMergeAuto.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationMergeFirstTran.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationMergeImport.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-987
> Fix bug where merge-type=import sets state to New

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-1013
> fix(merge translation): fix merge translation exception with new translation

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/service/impl/CopyVersionServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-959
https://zanata.atlassian.net/browse/ZNTA-1000
> fix(ZNTA-959,ZNTA-1000): Add try catch for copy version task

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/VersionHome.java
- zanata-war/src/main/java/org/zanata/service/impl/CopyVersionServiceImpl.java
- zanata-war/src/test/java/org/zanata/service/impl/CopyVersionServiceImplTest.java
https://zanata.atlassian.net/browse/ZNTA-1001
https://zanata.atlassian.net/browse/ZNTA-959
depending/related: https://github.com/zanata/zanata-server/pull/1127
> fix(copy version): fix null pointer exception when copy version

- functional-test/src/main/java/org/zanata/page/utility/Error404Page.java
- functional-test/src/test/java/org/zanata/feature/misc/PageNotFoundTest.java
- zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp-jboss/WEB-INF/web.xml
- zanata-war/src/main/webapp/404.xhtml
Don't give user a broken seam page on page or entity not found.
https://zanata.atlassian.net/browse/ZNTA-393
> Add a 404 page to Zanata

- docs/user-guide/translator-guide.md
In this trivial patch, I’ve added a synonym to avoid so many “click on…”, corrected prepositions and tenses, and fixed the phrasal verb “to log in”.
> docs: improve English in translator-guide.md

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/java/org/zanata/events/DocumentLocaleKey.java
- zanata-war/src/main/java/org/zanata/events/TextFlowTargetStateEvent.java
- zanata-war/src/main/java/org/zanata/service/impl/ActivityServiceImpl.java
- zanata-war/src/main/java/org/zanata/service/impl/CopyTransWorkFactory.java
- zanata-war/src/main/java/org/zanata/service/impl/MergeTranslationsServiceImpl.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationStateCacheImpl.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationUpdatedManager.java
- zanata-war/src/main/java/org/zanata/service/impl/VersionStateCacheImpl.java
- zanata-war/src/test/java/org/zanata/service/impl/ActivityServiceImplTest.java
- zanata-war/src/test/java/org/zanata/service/impl/CopyTransServiceImplTest.java
- zanata-war/src/test/java/org/zanata/service/impl/MergeTranslationsServiceImplTest.java
- zanata-war/src/test/java/org/zanata/service/impl/TranslationStateCacheImplTest.java
- zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java
https://zanata.atlassian.net/browse/ZNTA-1017
> refactor(ZNTA-1017): translation updates event to handle batch

- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-languages.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab-languages.xhtml
https://zanata.atlassian.net/browse/ZNTA-1068
> fix(language list): refresh language list when add/remove language from project/version

- frontend/src/main/web/lib/components/SystemGlossary.jsx
https://zanata.atlassian.net/browse/ZNTA-1065
> fix(menu drop down): drop-down user menu does not obscure the Glossary button

- frontend/src/main/web/lib/components/MessageModal.jsx
https://zanata.atlassian.net/browse/ZNTA-1074
> fix(glossary notification): hide details section in notification dialog

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/ProjectHome.java
- zanata-war/src/main/resources/messages.properties
https://zanata.atlassian.net/browse/ZNTA-1066
> Update notification message for delete project

- zanata-war/src/main/java/org/zanata/servlet/DuplicateParamFilter.java
- zanata-war/src/test/java/org/zanata/servlet/DuplicateParamFilterTest.java
https://zanata.atlassian.net/browse/ZNTA-1060
> fix(ZNTA-1060): avoid NPE in DuplicateParamFilter

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/webtrans/client/keys/Keys.java
- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/EditorKeyShortcuts.java
- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TargetContentsPresenter.java
- zanata-war/src/main/java/org/zanata/webtrans/client/resources/TableEditorMessages.java
- zanata-war/src/test/java/org/zanata/webtrans/client/presenter/EditorKeyShortcutsTest.java
https://zanata.atlassian.net/browse/ZNTA-746
> feat(shortcut): add shortcut for approve and reject translation

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/file/SourceDocumentUpload.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-981
> fix(File upload): Remove file extension for gettext type upload in UI

- zanata-war/src/main/java/org/zanata/dao/AccountResetPasswordKeyDAO.java
- zanata-war/src/main/java/org/zanata/jpa/EntityManagerProducer.java
https://zanata.atlassian.net/browse/ZNTA-931
> fix(ZNTA-931): incorrect scopes

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-1086
> fix(translation): check for null target when performing translation

- zanata-war/src/main/java/org/zanata/events/TextFlowTargetStateEvent.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
https://zanata.atlassian.net/browse/ZNTA-1084
> fix(ZNTA-1084): NoSuchElementException in event handler

- docs/user-guide/system-admin/configuration/installation.md
- zanata-war/src/main/java/org/zanata/rest/ZanataRestResponseInterceptor.java
https://zanata.atlassian.net/browse/ZNTA-1042
Rebase of https://github.com/zanata/zanata-server/pull/1149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1156)
> ZNTA-1042 Control CORS with system property

- zanata-war/src/main/java/org/zanata/action/VersionHome.java
https://zanata.atlassian.net/browse/ZNTA-1119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1177)
> fix(copy version): fix copy version message

- pom.xml
- zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java
https://zanata.atlassian.net/browse/ZNTA-1120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1176)
> fix(doc status): Fix doc status api endpoint (#1120)

- zanata-war/src/main/java/org/zanata/action/ProjectHome.java
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml
https://zanata.atlassian.net/browse/ZNTA-1125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1180)
> fix(project settings): fix exception when set project to 'invite only'

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/ContactAdminAction.java
- zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version-group/request_join_modal.xhtml
https://zanata.atlassian.net/browse/ZNTA-846
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1179)
> fix(request join group): limit message field in request join group dialog

- zanata-war/src/main/java/org/zanata/action/VersionHome.java
https://zanata.atlassian.net/browse/ZNTA-1128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1184)
> fix(copy version): Entering a name before unchecking 'copy' breaks the list

- docs/release-notes.md
- zanata-war/src/main/java/org/zanata/action/ContactLanguageTeamMembersAction.java
- zanata-war/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java
- zanata-war/src/test/java/org/zanata/email/EmailStrategyTest.java
https://zanata.atlassian.net/browse/ZNTA-1130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1185)
> fix(contact language team member): remove replyTo email

- docs/user-guide/system-admin/configuration/document-storage-directory.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1181)
> Fix zanata.file.directory documentation

- docs/user-guide/system-admin/configuration/installation.md
- zanata-war/src/main/java/org/zanata/rest/ZanataRestResponseInterceptor.java
https://zanata.atlassian.net/browse/ZNTA-1131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1187)
> refactor(system property): rename zanata.originWhiteList to zanata.origin.whitelist

- zanata-war/src/main/resources/pluralforms.properties
Zanata is currently producing broken lt.po files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1175)
> Fix the lt Plural-Forms expression

- zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
- zanata-war/src/main/java/org/zanata/config/DatabaseBackedConfig.java
- zanata-war/src/main/java/org/zanata/jpa/NoNestingTransactionStrategy.java
- zanata-war/src/main/java/org/zanata/limits/RateLimitManager.java
- zanata-war/src/main/java/org/zanata/notification/EmailQueueMessageReceiver.java
- zanata-war/src/main/java/org/zanata/notification/LanguageTeamPermissionChangeJmsMessagePayloadHandler.java
- zanata-war/src/main/java/org/zanata/rest/service/IntrospectableObjectMonitorService.java
- zanata-war/src/main/java/org/zanata/util/ScopeHelper.java
- zanata-war/src/test/java/org/zanata/notification/EmailQueueMessageReceiverTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1174)
> fix(ZNTA-1116): use transaction when reading config from DB

- frontend/src/main/web/atomicCssConfig.js
- frontend/src/main/web/src/legacy.js
- zanata-war/pom.xml
- zanata-war/src/main/resources/org/zanata/webtrans/public/Application.xhtml
https://zanata.atlassian.net/browse/ZNTA-1140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1189)
> fix(gwt editor): fix css in gwt editor

- zanata-war/src/main/java/org/zanata/jpa/NoNestingTransactionStrategy.java
- zanata-war/src/main/java/org/zanata/limits/RateLimitManager.java
- zanata-war/src/main/java/org/zanata/notification/EmailQueueMessageReceiver.java
- zanata-war/src/main/java/org/zanata/notification/LanguageTeamPermissionChangeJmsMessagePayloadHandler.java
- zanata-war/src/main/java/org/zanata/rest/service/IntrospectableObjectMonitorService.java
- zanata-war/src/main/java/org/zanata/util/ScopeHelper.java
- zanata-war/src/test/java/org/zanata/notification/EmailQueueMessageReceiverTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1192)
> Fix merge release to master

- frontend/src/main/web/src/containers/App.js
- frontend/src/main/web/src/legacy.js
https://zanata.atlassian.net/browse/ZNTA-1164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1197)
> fix(side menu): fix ROOT context url path

- frontend/src/main/web/src/actions/glossary.js
- frontend/src/main/web/src/containers/Glossary/DeleteEntryModal.jsx
- frontend/src/main/web/src/containers/Glossary/Entry.js
- frontend/src/main/web/src/containers/Glossary/index.js
- frontend/src/main/web/src/reducers/glossary.js
https://zanata.atlassian.net/browse/ZNTA-1136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1199)
> feat(paging): replace glossary list with paging

- functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
- zanata-war/src/main/webapp/WEB-INF/layout/project/edit_form.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version-group/edit_form.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/edit_form.xhtml
- zanata-war/src/main/webapp/account/login.xhtml
- zanata-war/src/main/webapp/account/register.xhtml
https://zanata.atlassian.net/browse/ZNTA-27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1195)
> fix(focus): add auto focus in create form, login and signup page

- zanata-war/src/main/webapp/404.xhtml
Template used by 404 page was removed, update to existing template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1198)
> Fix the 404 page

- zanata-war/src/main/java/org/zanata/rest/service/ResourceUtils.java
- zanata-war/src/test/java/org/zanata/rest/service/raw/TranslationResourceRestITCase.java
https://zanata.atlassian.net/browse/ZNTA-1145
Reviewed in https://github.com/zanata/zanata-server/pull/1191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1205)
> fix(po file): Fix po-revision-date header

- frontend/src/main/web/src/containers/Glossary/Entry.js
https://zanata.atlassian.net/browse/ZNTA-1138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1196)
> fix(glossary): update list after delete glossary entry

- zanata-war/src/main/webapp/WEB-INF/layout/version-group/settings-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/template/banner.xhtml
https://zanata.atlassian.net/browse/ZNTA-1175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1207)
> Fix name use of messages bean to msgs

- frontend/src/main/web/src/containers/Glossary/EntryModal.js
- frontend/src/main/web/src/containers/Glossary/NewEntryModal.js
- frontend/src/main/web/src/utils/DateHelper.js
- frontend/src/main/web/src/utils/GlossaryHelper.js
https://zanata.atlassian.net/browse/ZNTA-1167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1200)
> fix(glossary info): include lastModifiedBy info in entry

- zanata-war/src/main/java/org/zanata/file/FileSystemPersistService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1210)
> fix error message on missing sys property

- zanata-war/src/main/java/org/zanata/action/AuthenticationEvents.java
- zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java
https://zanata.atlassian.net/browse/ZNTA-1182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1215)
> fix(login): fix new user login in kerberos

- zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1209)
> Add tooltip to dashboard remove language icon

- zanata-war/src/main/java/org/zanata/util/EssentialDataCreator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1186)
> Update 'no admin user' warning to refer to system properties

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1212)
> feat: upgrade to DeltaSpike 1.7.0

- docs/release-notes.md
- functional-test/src/main/java/org/zanata/page/projectversion/VersionDocumentsPage.java
- functional-test/src/test/java/org/zanata/feature/document/FileTypeUploadTest.java
- functional-test/src/test/java/org/zanata/feature/editor/TranslateTsTest.java
- pom.xml
- zanata-model/pom.xml
- zanata-war/pom.xml
- zanata-war/src/main/java/org/zanata/adapter/FileFormatAdapter.java
- zanata-war/src/main/java/org/zanata/adapter/HTMLAdapter.java
- zanata-war/src/main/java/org/zanata/adapter/OkapiFilterAdapter.java
- zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java
- zanata-war/src/main/java/org/zanata/rest/service/FileService.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
- zanata-war/src/main/java/org/zanata/util/EssentialDataCreator.java
- zanata-war/src/main/java/org/zanata/util/HtmlUtil.java
_Structured format, no fuzzy concept = translated_
_"there might be some bug in the skeleton of the second Start Group"._
Depends on:
- https://github.com/zanata/zanata-api/pull/35
- https://github.com/zanata/zanata-client/pull/102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/975)
> feat(document): Support Qt TS files

- frontend/src/main/web/src/components/NavItem.jsx
- frontend/src/main/web/src/index.js
- frontend/src/main/web/src/legacy.js
https://zanata.atlassian.net/browse/ZNTA-1213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1226)
> fix(profile): fix url for when deploy as ROOT.war

- docs/release-notes.md
- functional-test/pom.xml
- pom.xml
- zanata-overlay/config/remote-deps.groovy
- zanata-war/pom.xml
- zanata-war/src/main/java/org/zanata/dao/StreamingDAO.java
- zanata-war/src/main/java/org/zanata/dao/TextFlowStreamingDAO.java
- zanata-war/src/main/java/org/zanata/dao/TransMemoryStreamingDAO.java
- zanata-war/src/main/java/org/zanata/database/WrappedDatasourceConnectionProvider.java
- zanata-war/src/main/java/org/zanata/database/WrappedDriverManagerConnectionProvider.java
- zanata-war/src/main/webapp-jboss/WEB-INF/classes/META-INF/persistence.xml
https://zanata.atlassian.net/browse/ZNTA-1203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1222)
> Remove Hibernate module for WildFly

- functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectWebHooksTab.java
- functional-test/src/test/java/org/zanata/feature/glossary/GlossaryAdminTest.java
- functional-test/src/test/java/org/zanata/feature/glossary/GlossaryPushTest.java
- functional-test/src/test/java/org/zanata/feature/project/EditWebHooksTest.java
- zanata-war/src/main/java/org/zanata/action/ProjectHome.java
- zanata-war/src/main/java/org/zanata/webhook/events/TestEvent.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab.xhtml
https://zanata.atlassian.net/browse/ZNTA-1160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1225)
> feat(webhook): Test event for new webhook

- frontend/src/main/web/src/actions/profile.js
- frontend/src/main/web/src/containers/UserProfile/index.jsx
- frontend/src/main/web/webpack.config.js
- zanata-war/src/main/webapp/account/login.xhtml
fix(profile): redirect to login is user not logged in
https://zanata.atlassian.net/browse/ZNTA-1051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1228)
> fix(login redirect): preserves hash location after login

- frontend/src/main/web/src/actions/glossary.js
- frontend/src/main/web/src/containers/Glossary/index.js
- frontend/src/main/web/src/reducers/glossary.js
https://zanata.atlassian.net/browse/ZNTA-1168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1227)
> feat(glossary): page size selection

- docs/release-notes.md
- functional-test/pom.xml
- pom.xml
- zanata-overlay/config/remote-deps.groovy
- zanata-war/pom.xml
- zanata-war/src/main/java/org/zanata/dao/StreamingDAO.java
- zanata-war/src/main/java/org/zanata/dao/TextFlowStreamingDAO.java
- zanata-war/src/main/java/org/zanata/dao/TransMemoryStreamingDAO.java
- zanata-war/src/main/java/org/zanata/database/WrappedDatasourceConnectionProvider.java
- zanata-war/src/main/java/org/zanata/database/WrappedDriverManagerConnectionProvider.java
- zanata-war/src/main/webapp-jboss/WEB-INF/classes/META-INF/persistence.xml
Reverts zanata/zanata-server#1222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1232)
> Revert "Remove Hibernate module for WildFly"

- zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/StatisticsService.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/SuggestionsService.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/TextFlowService.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/TransUnitService.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/UserService.java
- zanata-war/src/main/java/org/zanata/rest/search/service/SearchService.java
- zanata-war/src/main/java/org/zanata/rest/service/FileService.java
- zanata-war/src/main/java/org/zanata/rest/service/IntrospectableObjectMonitorService.java
- zanata-war/src/main/java/org/zanata/rest/service/ProjectIterationLocalesService.java
- zanata-war/src/main/java/org/zanata/rest/service/ProjectLocalesService.java
- zanata-war/src/main/java/org/zanata/rest/service/ProjectsService.java
- zanata-war/src/main/java/org/zanata/rest/service/ServerConfigurationService.java
- zanata-war/src/main/java/org/zanata/rest/service/StatisticsServiceImpl.java
- zanata-war/src/main/java/org/zanata/service/SearchIndexManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1223)
> Use read-only transactions

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1119)
> Simplify parent

- zanata-war/src/main/java/org/zanata/security/ZanataOpenId.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1242)
> fix(ZNTA-1112): remove messages prior to openid auth

- functional-test/pom.xml
- zanata-test-war/pom.xml
- zanata-war/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1240)
> chore: don't deploy zanata-test-war/functional-test

- docker/Dockerfile
- docker/rundev.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1243)
> chore: enable docker dev image app server debugging

- zanata-war/src/main/java/org/zanata/database/ConnectionWrapper.java
- zanata-war/src/main/java/org/zanata/database/ResultSetWrapper.java
- zanata-war/src/main/java/org/zanata/database/StatementWrapper.java
- zanata-war/src/test/java/org/zanata/ZanataJpaTest.java
- zanata-war/src/test/java/org/zanata/database/ConnectionWrapperTransactionTest.java
- zanata-war/src/test/java/org/zanata/database/WrappedConnectionProviderTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1231)
> Detect incomplete transactions during tests

- zanata-war/src/main/java/org/zanata/dao/GlossaryDAO.java
- zanata-war/src/main/java/org/zanata/service/TranslationMemoryService.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/GlossaryView.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TranslationMemoryDisplay.java
- zanata-war/src/main/java/org/zanata/webtrans/server/rpc/GetGlossaryHandler.java
- zanata-war/src/main/java/org/zanata/webtrans/shared/rpc/LuceneQuery.java
https://zanata.atlassian.net/browse/ZNTA-697
https://zanata.atlassian.net/browse/ZNTA-688
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1249)
> fix(tm,glossary): limit length of lucene query

- functional-test/src/main/java/org/zanata/page/AbstractPage.java
- functional-test/src/test/java/org/zanata/feature/administration/EditTranslationMemoryTest.java
https://zanata.atlassian.net/browse/ZNTA-1278
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1253)
> fix(js alert): disable js alert tests due to issue with chromedriver

- zanata-war/src/main/java/org/zanata/security/ZanataOpenId.java
https://zanata.atlassian.net/browse/ZNTA-1275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1252)
> fix(openid): fix encoding issue with openid login

- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-languages.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/project/versions-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab-languages.xhtml
https://zanata.atlassian.net/browse/ZNTA-608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1248)
> fix(editor url): Fix source lang in editor url

- functional-test/src/main/java/org/zanata/page/administration/TranslationMemoryPage.java
- functional-test/src/test/java/org/zanata/feature/administration/EditTranslationMemoryTest.java
- zanata-war/src/main/java/org/zanata/action/RoleAssignmentRuleAction.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/admin/rolemanager.xhtml
- zanata-war/src/main/webapp/admin/rolerules.xhtml
- zanata-war/src/main/webapp/admin/usermanager.xhtml
- zanata-war/src/main/webapp/resources/zanata/confirm-modal.xhtml
- zanata-war/src/main/webapp/tm/home.xhtml
https://zanata.atlassian.net/browse/ZNTA-1283
Original PR and reviewed:
https://github.com/zanata/zanata-server/pull/1256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1259)
> Migrate js alert and js confirm for admin pages

- zanata-war/pom.xml
https://zanata.atlassian.net/browse/ZNTA-1307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1263)
> Upgrade to JavaMelody 1.60.0

- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml
- zanata-war/src/main/webapp/language/home.xhtml
- zanata-war/src/main/webapp/resources/zanata/ajax-command-button.xhtml
https://zanata.atlassian.net/browse/ZNTA-1286
Based off: https://github.com/zanata/zanata-server/pull/1259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1258)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/zanata/zanata-server/pull/1258%23issuecomment-236081054%22%2C%20%22https%3A//github.com/zanata/zanata-server/pull/1258%23issuecomment-236471152%22%2C%20%22https%3A//github.com/zanata/zanata-server/pull/1258%23issuecomment-236838837%22%2C%20%22https%3A//github.com/zanata/zanata-server/pull/1258%23discussion_r72915502%22%2C%20%22https%3A//github.com/zanata/zanata-server/pull/1258%23discussion_r72915889%22%5D%2C%20%22co …
> Language/Dashboard: migrate js alert and js confirm to modal

- zanata-war/src/main/webapp/project/home.xhtml
https://zanata.atlassian.net/browse/ZNTA-1317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1267)
> fix(project list): disable sorting in project list to prevent db error

- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/project/versions-tab.xhtml
- zanata-war/src/main/webapp/project/home.xhtml
- zanata-war/src/main/webapp/project/project.xhtml
https://zanata.atlassian.net/browse/ZNTA-1284
Based off: https://github.com/zanata/zanata-server/pull/1258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1260)
> refactor(project pages): migrate js confirm to modal

- docker/conf/admin-user-setup.sql
- zanata-war/src/main/java/org/zanata/rest/service/FileService.java
https://zanata.atlassian.net/browse/ZNTA-1023
https://zanata.atlassian.net/browse/ZNTA-1248
Requires https://github.com/zanata/zanata-api/pull/56
Enables https://github.com/zanata/zanata-client/pull/113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1244)
> feat(ZNTA-1023): add FileService.fileTypeInfoList()

- docker/conf/standalone.xml
- functional-test/src/test/resources/datasource/zanata-ds.xml
- zanata-overlay/distros/eap-6/standalone/configuration/standalone-zanata.xml
- zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml
- zanata-war/src/main/java/org/zanata/ui/TransactionPhaseListener.java
- zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
- zanata-war/src/test/resources/arquillian/standalone-arquillian.xml
https://zanata.atlassian.net/browse/ZNTA-1318
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1268)
> Improve JDBC error handling

- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/merge_trans_modal.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/zip_download_progress_modal.xhtml
- zanata-war/src/main/webapp/iteration/view.xhtml
- zanata-war/src/main/webapp/resources/zanata/confirm-modal.xhtml
- zanata-war/src/main/webapp/resources/zanata/version-copy-action-loader.xhtml
- zanata-war/src/main/webapp/tm/home.xhtml
https://zanata.atlassian.net/browse/ZNTA-1285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1266)
> refactor(version pages): migrate confirm to modal

- zanata-frontend/pom.xml
https://zanata.atlassian.net/browse/ZNTA-1337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1271)
> fix(build): Exclude node_modules from zanata-frontend build

- zanata-war/src/main/java/org/zanata/ui/TransactionPhaseListener.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1255)
> Ensure commit/rollback only once

- zanata-war/src/main/java/org/zanata/servlet/CharacterEncodingFilter.java
- zanata-war/src/main/webapp-jboss/WEB-INF/web.xml
https://zanata.atlassian.net/browse/ZNTA-1323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1270)
> fix(encoding): force utf8 encoding for /account/ request

- zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml
See https://access.redhat.com/solutions/309913
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1254)
> Disable exception in case of JDBC leak

- zanata-war/src/main/java/org/zanata/action/LoginAction.java
- zanata-war/src/main/java/org/zanata/action/OpenIdAction.java
- zanata-war/src/main/java/org/zanata/security/OpenIdPhaseListener.java
- zanata-war/src/main/java/org/zanata/util/UrlUtil.java
- zanata-war/src/main/resources/org/zanata/webtrans/public/Application.xhtml
- zanata-war/src/main/webapp/WEB-INF/faces-config.xml
- zanata-war/src/main/webapp/openid.xhtml
https://zanata.atlassian.net/browse/ZNTA-1340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1275)
> fix(openid redirect): redirect to user url after openid login

- zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
https://zanata.atlassian.net/browse/ZNTA-1293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1274)
> Fix(ZNTA-1293): remove cid param

- zanata-frontend/src/editor/__tests__/components/ProgressBarTest.js
- zanata-frontend/src/editor/__tests__/components/TransUnitFilterTest.js
- zanata-frontend/src/editor/app/components/ProgressBar/index.css
- zanata-frontend/src/editor/app/components/ProgressBar/index.js
- zanata-frontend/src/editor/app/components/TransUnit/index.css
- zanata-frontend/src/editor/app/components/TransUnit/index.js
- zanata-frontend/src/editor/app/components/TransUnitFilter.js
- zanata-frontend/src/editor/app/components/TransUnitTranslationFooter.js
- zanata-frontend/src/editor/app/containers/EditorHeader/index.js
- zanata-frontend/src/editor/app/reducers/headerData.js
- zanata-frontend/src/editor/app/reducers/ui.js
- zanata-frontend/src/editor/app/utils/Util.js
- zanata-frontend/src/editor/app/utils/status.js
https://zanata.atlassian.net/browse/ZNTA-132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1277)
> rejected state in redux  ZNTA-132

- docker/rundev.sh
See also https://github.com/zanata/zanata-server/pull/1279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1281)
> Enable heap dump on OOM

- docker/Dockerfile
- docs/user-guide/system-admin/configuration/installation.md
- pom.xml
- zanata-war/src/main/java/org/zanata/ZanataInit.java
https://zanata.atlassian.net/browse/ZNTA-1358
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1282)
> fix(ZNTA-1358) upgrade to WildFly 10.1

- docker/rundev.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1293)
> docker script - check war file before chcon

- docker/conf/standalone.xml
- docker/rundev.sh
- functional-test/src/test/resources/conf/standalone.xml
- functional-test/src/test/resources/conf/standalone_wildfly.xml
- zanata-overlay/distros/eap-7/standalone/configuration/standalone-zanata.xml
- zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml
- zanata-war/src/main/java/org/zanata/action/CacheAction.java
- zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
- zanata-war/src/test/resources/arquillian/standalone-arquillian.xml
https://zanata.atlassian.net/browse/ZNTA-1363
See also https://zanata.atlassian.net/browse/ZNTA-1364, https://issues.jboss.org/browse/WFLY-3377 and https://issues.jboss.org/browse/ISPN-5421
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1284)
> fix(ZNTA-1363): handle stats being disabled

- functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1295)
> Skip screenshot for screenshot exceptions

- zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java
https://zanata.atlassian.net/browse/ZNTA-1392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1294)
> fix(docId): handle comma separated docId

- zanata-war/src/main/java/org/zanata/action/VersionGroupHomeAction.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/dashboard/groups.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version-group/languages-tab.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version-group/projects-tab.xhtml
- zanata-war/src/main/webapp/iteration/view.xhtml
- zanata-war/src/main/webapp/project/project.xhtml
- zanata-war/src/main/webapp/resources/zanata/loader.xhtml
- zanata-war/src/main/webapp/version-group/version_group.xhtml
https://zanata.atlassian.net/browse/ZNTA-527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1292)
> fix(stats loading): fix stats loading in project, version, group page

- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TranslationHistoryView.java
https://zanata.atlassian.net/browse/ZNTA-1384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1289)
> fix(editor history): reset view when editor history shows

- zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml
https://zanata.atlassian.net/browse/ZNTA-421
This is the branch that needs to be merged. I will close the other pull request (https://github.com/zanata/zanata-server/pull/1296).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1298)
> ZNTA-421 Swap TM highlighting

- functional-test/pom.xml
- zanata-war/src/test/resources/arquillian.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1303)
> Ensure full stack traces and heap dumps in tests

- functional-test/pom.xml
- functional-test/src/test/java/org/zanata/feature/clientserver/GettextPluralSupportTest.java
- functional-test/src/test/java/org/zanata/feature/clientserver/ProjectMaintainerTest.java
- functional-test/src/test/java/org/zanata/feature/clientserver/PropertiesRoundTripTest.java
- functional-test/src/test/java/org/zanata/feature/concurrentedit/ConcurrentAccessTest.java
- functional-test/src/test/java/org/zanata/feature/glossary/GlossaryAdminTest.java
- functional-test/src/test/java/org/zanata/feature/glossary/GlossaryPushTest.java
- functional-test/src/test/java/org/zanata/feature/glossary/InvalidGlossaryPushTest.java
- functional-test/src/test/java/org/zanata/feature/misc/RateLimitRestAndUITest.java
- functional-test/src/test/java/org/zanata/util/SampleDataResourceClient.java
- functional-test/src/test/java/org/zanata/util/ZanataRestCaller.java
- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1299)
> ZNTA-1271 make functional-test to use resteasy

- zanata-war/src/main/java/org/zanata/action/CopyTransAction.java
- zanata-war/src/main/webapp/WEB-INF/layout/copy_trans_inline.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/copy_trans_inline_modal.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
https://zanata.atlassian.net/browse/ZNTA-1400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1300)
> fix(copytrans): update copytrans options when run

- zanata-war/src/main/java/org/zanata/action/LanguageAction.java
https://zanata.atlassian.net/browse/ZNTA-1404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1305)
> fix(language role): update language role change event

- zanata-war/src/main/webapp/WEB-INF/template/scripts.xhtml
https://zanata.atlassian.net/browse/ZNTA-1386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1291)
> fix(ZNTA-1386): update Piwik code (async), add image tracker

- zanata-model/src/main/java/org/zanata/util/JaxRSClassIndexProcessor.java
- zanata-test-war/src/main/java/org/zanata/rest/SampleDataResource.java
- zanata-war/src/main/java/org/zanata/rest/Application.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/ProjectResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/StatisticResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/SuggestionsResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/TextFlowResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/TransUnitResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/TranslationResource.java
- zanata-war/src/main/java/org/zanata/rest/editor/service/resource/UserResource.java
- zanata-war/src/main/java/org/zanata/service/SearchService.java
Depends on https://github.com/zanata/zanata-api/pull/45 (won't compile without it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1118)
> ZNTA-1328 Use RestResource for JAX-RS Application classes set

- zanata-war/src/main/java/org/zanata/webtrans/client/Application.java
- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/AppPresenter.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TransUnitDetailsPanel.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/TransUnitDetailsPanel.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/view/SourceContentsView.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/SourceContentsView.ui.xml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-16
Update bookmark link in editor to be more meaningful and visible
- Code quality
- Testing
---- …
> refactor(bookmark): Update bookmark button in editor

- zanata-frontend/src/frontend/app/actions/profile.js
- zanata-frontend/src/frontend/app/constants/Options.js
- zanata-frontend/src/frontend/app/containers/UserProfile/CalendarMonthMatrix.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/CalendarPeriodHeading.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/CategoryItemMatrix.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/CategoryMatrixTable.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/ContributionChart.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/FilterableMatrixTable.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/RecentContributions.jsx
- zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
- zanata-frontend/src/frontend/app/reducers/profile.js
- zanata-frontend/src/frontend/app/utils/DateHelper.js
- zanata-frontend/src/frontend/npm-shrinkwrap.json
- zanata-frontend/src/frontend/package.json
https://zanata.atlassian.net/browse/ZNTA-1366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1287)
> feat(profile): selective date range

- docker/README.md
- docker/rundev.sh
*Customize docker dev run script*
Provides support for offsetting the container listening ports. Also provide support to deploy an exploded war. One drawback will be it now requires the host machine to have mysql-connector-java package installed.
- Code quality
- Testing
[Considerations for new …
> Docker script

- pom.xml
JIRA issue URL: *[paste URL here]*
*[Add a short description of what is changed here.]*
- Code quality
- Testing
---- …
> Update to RichFaces 4.5.17.Final

- functional-test/pom.xml
- pom.xml
- zanata-war/pom.xml
JIRA issue URL: *[paste URL here]*
*[Add a short description of what is changed here.]*
- Code quality
- Testing
---- …
> Update to RESTEasy 3.0.19.Final

- etc/scripts/quickbuild.sh
- zanata-war/src/main/java/org/zanata/webtrans/client/presenter/UserConfigHolder.java
- zanata-war/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java
- zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/CellTableResources.css
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.java
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/SearchResultsView.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/SearchResultsView.ui.xml
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
- zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml
- zanata-war/src/test/java/org/zanata/webtrans/client/presenter/TransMemoryPresenterTest.java
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-421*
*TM diff color update*
- Code quality
- Testing
---- …
> ZNTA-421 - tm-highlighting

- docker/Dockerfile
- docker/README.md
- docker/conf/mysql-module/com/mysql/main/module.xml
- docker/conf/standalone.xml
- docker/rundev.sh
update docker image file and docker run script:
- docker image will create a mysql module and use that. No more jar file to deploy.
- map a folder as docker volume to jboss deployments folder. Now you can just hard link your war file to that folder. Rebuild the war will get automatically picked up by jboss. Deploying exploded war is also possible.
- Code quality
- If …
> update docker script

- zanata-war/src/main/java/org/zanata/webtrans/client/resources/RpcMessages.java
- zanata-war/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java
JIRA issue URL: None
Changed wording of error and empty results messages
- Code quality
- Testing
---- …
> fix(editor): Improve some error messages

- docs/user-guide/documents/raw-documents.md
- functional-test/src/test/java/org/zanata/feature/editor/TranslateJSONTest.java
- functional-test/src/test/java/org/zanata/feature/testharness/TestPlan.java
- pom.xml
- zanata-war/pom.xml
- zanata-war/src/main/java/org/zanata/adapter/JsonAdapter.java
- zanata-war/src/main/java/org/zanata/service/impl/TranslationFileServiceImpl.java
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml
Depends https://github.com/zanata/zanata-api/pull/58
Related to https://github.com/zanata/zanata-client/pull/125
https://zanata.atlassian.net/browse/ZNTA-86
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1261)
Was partially reviewed in Gitcolony: https://www.gitcolony.com/#/Zanata/review-pull/2148/49807 but now back in Reviewable (linked above).
> Basic JSON support

- zanata-model/src/main/java/org/zanata/model/WebHook.java
- zanata-model/src/main/java/org/zanata/model/type/WebhookType.java
- zanata-war/src/main/java/org/zanata/action/ProjectHome.java
- zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
- zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java
- zanata-war/src/main/java/org/zanata/service/ProjectService.java
- zanata-war/src/main/java/org/zanata/service/impl/ProjectServiceImpl.java
- zanata-war/src/main/java/org/zanata/service/impl/WebhookServiceImpl.java
- zanata-war/src/main/java/org/zanata/webhook/events/ManuallyTriggeredEvent.java
- zanata-war/src/main/resources/db/changelogs/db.changelog-4.0.xml
- zanata-war/src/main/resources/messages.properties
- zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-webhook.xhtml
- zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
- zanata-war/src/main/webapp/resources/script/components-script.js
- zanata-war/src/main/webapp/resources/zanata/webbook-form.xhtml
- zanata-war/src/test/java/org/zanata/search/FilterConstraintToQueryJpaTest.java
- zanata-war/src/test/java/org/zanata/service/impl/DocumentServiceImplTest.java
- zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java
JIRA issue URL: *[https://zanata.atlassian.net/browse/ZNTA-1290]*
*Can create a webhook and trigger it manually*
- Code quality
- Testing
----
*This template …
> ZNTA-1290 - manually triggered webhook
