pom.xml

If Sourceforge is in "Disaster Recovery mode", you will need to download the module zips to `~/Downloads` using your browser, from here: http://sourceforge.net/projects/zanata/files/wildfly/

Cache downloaded wildfly modules to ~/Downloads

---

functional-test/src/test/java/org/zanata/feature/language/ContactLanguageTeamTest.java
zanata-war/src/main/java/org/zanata/action/ContactAdminAction.java
zanata-war/src/main/java/org/zanata/action/SendEmailAction.java
zanata-war/src/main/java/org/zanata/email/EmailBuilder.java
zanata-war/src/main/java/org/zanata/notification/LanguageTeamPermissionChangeJmsMessagePayloadHandler.java
zanata-war/src/main/java/org/zanata/service/EmailService.java
zanata-war/src/main/java/org/zanata/service/impl/EmailServiceImpl.java
zanata-war/src/main/resources/messages.properties
zanata-war/src/main/resources/org/zanata/email/templates/template_email.vm
zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal.xhtml
zanata-war/src/main/webapp/WEB-INF/layout/language/contact_coordinator_modal.xhtml
zanata-war/src/main/webapp/WEB-INF/template/footer.xhtml
zanata-war/src/main/webapp/WEB-INF/urlrewrite.xml
zanata-war/src/main/webapp/language/language.xhtml
zanata-war/src/test/java/org/zanata/email/EmailStrategyTest.java

https://bugzilla.redhat.com/show_bug.cgi?id=1197572

Implement email reasons for admin

---

functional-test/src/test/resources/conf/standalone.xml
functional-test/src/test/resources/conf/standalone_wildfly.xml
zanata-overlay/distros/eap-6/standalone/configuration/standalone-zanata.xml
zanata-overlay/distros/wildfly-8.1/standalone/configuration/standalone-zanata.xml
zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
zanata-war/src/test/resources/arquillian/standalone-arquillian.xml

We really need to generate these files from a template, or perhaps a template for EAP and one for WildFly.

Reduce unnecessary log warnings

---

docs/configuration/infinispan.md
pom.xml
zanata-model/src/main/java/org/zanata/model/HAccount.java
zanata-model/src/main/java/org/zanata/model/HAccountResetPasswordKey.java
zanata-model/src/main/java/org/zanata/model/HCopyTransOptions.java
zanata-model/src/main/java/org/zanata/model/HDocument.java
zanata-model/src/main/java/org/zanata/model/HGlossaryEntry.java
zanata-model/src/main/java/org/zanata/model/HGlossaryTerm.java
zanata-model/src/main/java/org/zanata/model/HLocale.java
zanata-model/src/main/java/org/zanata/model/HPerson.java
zanata-model/src/main/java/org/zanata/model/HProject.java
zanata-model/src/main/java/org/zanata/model/HProjectIteration.java
zanata-model/src/main/java/org/zanata/model/HRoleAssignmentRule.java
zanata-model/src/main/java/org/zanata/model/HSimpleComment.java
zanata-model/src/main/java/org/zanata/model/HTermComment.java
zanata-model/src/main/java/org/zanata/model/HTextFlow.java
zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java
zanata-model/src/main/java/org/zanata/model/po/HPoHeader.java
zanata-model/src/main/java/org/zanata/model/po/HPoTargetHeader.java
zanata-model/src/main/java/org/zanata/model/po/HPotEntryData.java
zanata-war/pom.xml
zanata-war/src/main/webapp-jboss/WEB-INF/classes/META-INF/persistence.xml
zanata-war/src/test/resources/arquillian/persistence.xml

At least until a solution is found in terms of compatibility between Wildfly (hibernate 4.3, infinispan 6) and EAP (hibernate 4.2, infinispan 5).
Other data caches will still use infinispan.
The main reverted commit is: c513552187f78dcf7db96af66c6f2b6236c85a71
Parts of these commits were also reverted: 
0fa0a8ea34fe1a5c6463daa29f70f081748df0e4
f1a16afa548e0337514d5a093cf8d6938f08c234

Move back to Ehcache for hibernate 2nd level cache.

---

functional-test/src/test/resources/conf/standalone.xml
functional-test/src/test/resources/conf/standalone_wildfly.xml
zanata-overlay/distros/eap-6/standalone/configuration/standalone-zanata.xml
zanata-overlay/distros/wildfly-8.1/standalone/configuration/standalone-zanata.xml
zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
zanata-war/src/test/resources/arquillian/standalone-arquillian.xml

Changes the timeout to 1000 seconds (16min 40s) from default 300s (5min)
to prevent timeout when liquibase changesets take longer than 5 minutes
to run.
Already reviewed and verified in https://github.com/zanata/zanata-server/pull/735 and was a clean cherry-pick.

Increase timeout on server startup in all standalone.xml files.

---

docs/release-notes.md
zanata-war/src/main/webapp/WEB-INF/layout/version/merge_trans_modal.xhtml

These are the final changes for https://github.com/zanata/zanata-server/pull/738 that could not be applied on `release` branch.

Update version display for version merge, add release notes entry.

---

zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java

We get `hasPermission` denials all the time, so they are just noise.

Log as DEBUG when permission is denied (not WARN)

---

zanata-war/src/main/resources/db/changelogs/db.changelog-3.7.xml

The constraints which were dropped by changeset db.changelog-1.6a.xml:1:aeng@redhat.com were never reinstated, so this changeset puts them back.  (Discovered while investigating https://bugzilla.redhat.com/show_bug.cgi?id=1048293)
Note: this change is untested, and to test it will require running Zanata server against a persistent H2 database.  That isn't something we normally do these days, but I want to record this for completeness, and in case we ever want to run Zanata against H2 in future (eg for demos or quickstarts).
TODO (some time): Add a basic test which deploys Zanata on H2, thus validating that our liquibase changesets at least work on an empty H2 database.  Trying to be database-agnostic might help with future migration, eg https://bugzilla.redhat.com/show_bug.cgi?id=1205945

Restore constraints on glossary tables for H2

---

functional-test/src/main/java/org/zanata/page/CorePage.java
functional-test/src/test/java/org/zanata/feature/projectversion/EditVersionValidationsTest.java

We can assume, in cases other than testing the error page, that
the error page should not be seen when transitioning between
other pages.  Add a check in the constructor for all core pages
of Zanata.

Check errors when a test page is created/returned

---

zanata-war/src/main/java/org/zanata/util/HttpUtil.java

Should fix this intermittent unit test failure:
java.lang.NullPointerException: null
at org.zanata.util.HttpUtil.getClientIp(HttpUtil.java:95)
at org.zanata.rest.RestLimitingSynchronousDispatcher.invoke(RestLimitingSynchronousDispatcher.java:133)
at org.zanata.rest.RestLimitingSynchronousDispatcherTest.willProcessAnonymousWithGETAndNoApiKey(RestLimitingSynchronousDispatcherTest.java:123)

Handle missing/empty proxy header

---

functional-test/pom.xml
zanata-war/src/main/resources/db/changelogs/db.changelog-1.5.xml

https://bugzilla.redhat.com/show_bug.cgi?id=1048293

rhbz1048293 Fix liquibase changeset to be compatible with mysql/mariadb version > 5.5

---

docs/.gitattributes

This should prevent merge conflicts due to ~~changelog~~ release notes updates.

Set merge=union for release-notes.md in .gitattributes

---

functional-test/src/main/java/org/zanata/page/CorePage.java

See https://github.com/zanata/zanata-server/commit/25bf1e2dcb5bdc827ad23c89ed04368f7c3a024c#commitcomment-10769838
After this is merged:

Skip checking of critical errors (too slow due to implicit wait)

---

functional-test/src/main/java/org/zanata/page/AbstractPage.java
functional-test/src/test/java/org/zanata/feature/account/ProfileTest.java

Requires the class 'is-active' to be present in the web element,
as the loader is always present and visible.

Wait for page loaders to be finished before proceeding

---

docs/release-notes.md
zanata-model/src/main/java/org/zanata/model/HAccount.java
zanata-model/src/main/java/org/zanata/model/HAccountRole.java
zanata-model/src/main/java/org/zanata/model/HIterationGroup.java
zanata-model/src/main/java/org/zanata/model/HLocale.java
zanata-model/src/main/java/org/zanata/model/HLocaleMember.java
zanata-model/src/main/java/org/zanata/model/HProject.java
zanata-model/src/main/java/org/zanata/model/HProjectIteration.java
zanata-model/src/main/java/org/zanata/model/HasUserFriendlyToString.java
zanata-war/src/main/java/org/zanata/rest/AuthorizationExceptionMapper.java
zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java
zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java

https://bugzilla.redhat.com/show_bug.cgi?id=903964
For example, when invoke client with following command:
```z  -B push --push-type trans --merge-type import```
There are two(maybe more) possible permission failure:
* user is not part of the language team
* user don't have permission to do merge type import operation
In the past what we get back is just a 401 with no body in response. Now we can tell what exactly go wrong:
* when user is not a member for the locale
```
[ERROR] Execution failed: 
* Error Message: PUT http://localhost:8080/zanata/rest/async/projects/p/jasper/iterations/i/1/r/MessageResources/translations/de?ext=comment&merge=import&assignCreditToUploader=false returned a response status of 401 Unauthorized;
* Response From Server: Failed to obtain …
```

rhbz903964 - produce better error message when permission check failed

---

docs/release-notes.md
pom.xml
zanata-liquibase/pom.xml
zanata-liquibase/src/main/java/liquibase/ext/CreateTableGeneratorInnoDB.java
zanata-liquibase/src/main/java/liquibase/ext/MySQLDatabaseWithLog.java
zanata-war/pom.xml
zanata-war/src/main/java/liquibase/sqlgenerator/ext/CreateTableGeneratorInnoDB.java
zanata-war/src/main/resources/db/changelogs/db.changelog-1.0.xml
zanata-war/src/main/resources/db/changelogs/db.changelog-3.6.xml
zanata-war/src/main/resources/db/changelogs/db.changelog-3.7.xml
zanata-war/src/main/resources/db/changelogs/db.changelog-validations.xml
zanata-war/src/main/resources/db/db.changelog.xml

https://bugzilla.redhat.com/show_bug.cgi?id=1207575

Ensure use of InnoDB engine on MySQL

---

functional-test/src/main/java/org/zanata/page/AbstractPage.java
functional-test/src/test/java/org/zanata/feature/account/ProfileTest.java
functional-test/src/test/java/org/zanata/feature/account/RegisterTest.java
zanata-war/pom.xml

https://bugzilla.redhat.com/show_bug.cgi?id=1216304
This should help with the `form__loader` problem seen when testing http://assets-zanata.rhcloud.com/6.1.1/styleguide/

Update to zanata assets 6.1.1

---

zanata-war/src/main/java/org/zanata/util/CommonMarkRenderer.java

https://bugzilla.redhat.com/show_bug.cgi?id=1224594
This should prevent the error `org.mozilla.javascript.EvaluatorException: Property "├?" already defined in this object literal.` when loading `commonMarkRenderer` on the home page under Windows.

rhbz1224594 Ensure UTF-8 when reading commonmark.min.js

---

functional-test/src/test/java/org/zanata/feature/misc/FlakyTest.java
pom.xml

We can't release Zanata with a SNAPSHOT dependency, so we will have to downgrade for the moment.

Downgrade Surefire for release

---

zanata-war/src/main/webapp-jboss/WEB-INF/jboss-deployment-structure.xml

https://bugzilla.redhat.com/show_bug.cgi?id=1228086
This fixes java.lang.ClassNotFoundException: 
sun.security.action.GetPropertyAction when loading the projects page,
on JBoss EAP 6.4.0 installed via rpm.

Fix ClassNotFoundException on EAP rpm: rhbz1228086

---

frontend/README.md
frontend/pom.xml

It will install node and npm into $user.home/Downloads.
It will also try to use npm cache as much as possible.

Make frontend module more offline friendly

---

etc/scripts/extractAppserver.groovy
functional-test/pom.xml
pom.xml
zanata-war/pom.xml
zanata-war/src/etc/dependencyVersions.groovy

This should make it easier to switch between EAP and WildFly for testing.  Assuming you have set `EAP6_URL`, and you're happy to use the version of WildFly specified in the pom, you just switch between `-Dappserver=jbosseap6` and `-Dappserver=wildfly8`.  
No need to specify any of these (and it's easier to switch if you don't):
- cargo.installation
- cargo.basename
- appserver.dir.name
You can still specify these if you want to change the version of WildFly itself or the version of the management api:
- wildfly.version
- wildfly.client.version

Simplify appserver properties

---

zanata-war/src/main/webapp-jboss/WEB-INF/jboss-deployment-structure.xml

This was causing a deployment failure on JBoss EAP 6.3.3 with a root cause of
java.lang.ClassNotFoundException: javax.jms.MessageListener
from [Module "deployment.zanata.war:main" from Service Module Loader]
Related: https://issues.jboss.org/browse/WFLY-4642

Add explicit dependency on jms.

---

zanata-war/src/main/java/org/zanata/webtrans/Application.gwt.xml

This should reduce the size of zanata.war, and probably speed up builds
a bit too.

fix(gwt): avoid packaging .junit_symbolMaps/

---

zanata-war/src/test/java/org/zanata/SlowTest.java
zanata-war/src/test/java/org/zanata/rest/service/ResourceUtilsJpaTest.java
zanata-war/src/test/java/org/zanata/service/impl/CopyTransServiceImplPerformanceTest.java
zanata-war/src/test/java/org/zanata/service/impl/CopyTransServiceImplTest.java
zanata-war/src/test/java/org/zanata/service/impl/DocumentServiceImplTest.java

`@SlowTest` is currently not handled by our JUnit setup, so we have to `@Ignore` such tests, at least for now.

Ignore slow tests

---

pom.xml

Wildfly 10 alphas are in Maven, but currently not
http://wildfly.org/downloads/
This commit makes it easy to test against a WildFly alpha, just by setting the Maven property `wildfly.version`.
http://wildfly-development.1055759.n5.nabble.com/First-Alphas-of-WildFly-10-and-WildFly-Core-2-have-been-released-td5715883.html
http://wildfly-development.1055759.n5.nabble.com/10-0-0-Alpha2-released-amp-9-status-update-td5715967.html

Get wildfly zip from JBoss Maven repository

---

zanata-war/src/main/java/org/zanata/rest/service/ResourceUtils.java
zanata-war/src/test/java/org/zanata/rest/service/ResourceUtilsTest.java

Fall back on locale's plural forms when plurals header is empty.
Also simplify the code and improve log messages.

fix(ZNTA-628): fall back on locale's plural forms

---

zanata-war/src/main/java/org/zanata/rest/editor/service/SuggestionsService.java
zanata-war/src/main/java/org/zanata/rest/editor/service/resource/SuggestionsResource.java
zanata-war/src/main/java/org/zanata/service/TranslationMemoryService.java
zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
zanata-war/src/main/java/org/zanata/util/SysProperties.java

This PR builds on top of #923, by changing Lucene's scoring algorithm to favour results which share some or all of the same:
* TextFlowTarget (id)
* Project (slug)
* Iteration (slug)
* Document (docId)
* TextFlow (resId)

Boost Lucene query using TFT metadata

---

zanata-war/src/main/java/org/zanata/action/CopyTransAction.java
zanata-war/src/main/java/org/zanata/action/CopyTransManager.java

https://zanata.atlassian.net/browse/ZNTA-627
This should prevent server log messages like this one:
java.lang.IllegalArgumentException: Copy Trans can only run for HProjectIteration and HDocument
at org.zanata.action.CopyTransManager.isCopyTransRunning(CopyTransManager.java:80)
at sun.reflect.GeneratedMethodAccessor687.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInt …

fix(ZNTA-627): check whether project iteration is found

---

zanata-war/src/main/java/org/zanata/security/jaas/InternalLoginModule.java

This should make it easier for QA to switch between testing release and master, and also help anyone who follows the latest installation guide when deploying Zanata 3.7.

feat: add InternalLoginModule alias

---

pom.xml

We don't use Java 1.6 any more.

chore: use JVM version for tools jar

---

zanata-war/src/test/resources/META-INF/persistence.xml
zanata-war/src/test/resources/arquillian/persistence.xml

... instead of creating `zanatasearchindex` in current directory, which prevents `mvn clean` from doing its job (eg when Lucene lock files are lying around)

chore: move zanatasearchindex under target dir in tests

---

zanata-model/src/main/java/org/zanata/hibernate/search/DateBridge.java
zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java

Previously, our custom sort caused newer matches always to be favoured over highly-scored matches. Now we sort first by score, then by date.
See https://zanata.atlassian.net/browse/ZNTA-721

fix(ZNTA-721): pre-sort TM by Lucene score

---

zanata-war/src/main/resources/db/changelogs/db.changelog-3.7.xml
zanata-war/src/main/resources/db/mysql/add_missing_fks.sql

In the past, some Zanata environments defaulted to MyISAM for new
tables, and so some tables were MyISAM when we tried to create various
foreign keys. (MySQL silently ignores ADD FOREIGN KEY for MyISAM
tables.) This commit ensures that the affected foreign keys are
created if they don't exist.

Add any missing foreign keys

---

zanata-war/src/main/webapp-jboss/WEB-INF/web.xml

On some platforms, the MonitoringFilter has no init parameters
by the time requests come in, which causes JavaMelody to appear
under /monitoring instead of /admin/monitoring. This change uses
a servlet context parameter instead of a filter parameter.

Work around path problem for JavaMelody

---

zanata-war/src/main/resources/org/zanata/email/templates/email_request_to_join_language.vm

It was:
> You can add user with username "Some User" to the "xx" team as translator using the "Add Team Member" action on the language team page.
whereas it should have been:
> You can add user with username "some_username" to the "xx" team as translator using the "Add Team Member" action on the language team page.

Fix email message generated when user joining team

---

zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml

Currently the navigation to the version page, Document tab, and a
specific document is broken (when entering the url provided by Zanata
directly on the browser bar the server returns a 404). This commit
should fix that problem.

fix: url for documents with paths

---

pom.xml

Downgrade zanata-api version to point to release branch.
backport of https://github.com/zanata/zanata-server/pull/1029

Downgrade zanata-api to 3.8.3-SNAPSHOT

---

functional-test/src/main/java/org/zanata/page/AbstractPage.java
functional-test/src/main/java/org/zanata/page/WebDriverFactory.java
functional-test/src/main/java/org/zanata/page/WebDriverLogException.java
functional-test/src/test/java/org/zanata/feature/testharness/ZanataTestCase.java
zanata-war/src/main/java/org/zanata/action/AjaxCounterBean.java
zanata-war/src/main/webapp/WEB-INF/layout/project/languages-list.xhtml
zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml

Based on revised code from http://stackoverflow.com/a/4411986/14379
Also removing `setTimeout()` support: the `timeoutCounter` is not used, and
the wrapper code is causing problems.
This should eliminate the server error during `EditHomePageTest.editPageCode` and `EditProjectAboutTest.addAboutPageDetails`: `Uncaught TypeError: func is not a function`

Eliminate JS errors from functional tests

---

functional-test/src/main/java/org/zanata/page/dashboard/dashboardsettings/DashboardAccountTab.java
zanata-war/src/main/java/org/zanata/action/ValidateEmailAction.java
zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml

https://zanata.atlassian.net/browse/ZNTA-871
This will have the same issue as account activation where the message won't display but redirection works.
One of the solution I can think of is instead of using /account/validate_email/
{key} and /account/activate/{key}
to validate, use
http://localhost/zanata?validateEmail= {key}
* http://localhost/zanata?activateAccount={key}
With that, we can ensure message gets displayed properly.

fix(change email): redirection to home page after email change

---

zanata-war/src/main/java/org/zanata/WebAssetsConfiguration.java
zanata-war/src/main/java/org/zanata/rest/service/VersionService.java
zanata-war/src/main/java/org/zanata/service/impl/TranslationStateCacheImpl.java
zanata-war/src/main/java/org/zanata/service/impl/VersionStateCacheImpl.java
zanata-war/src/main/java/org/zanata/webtrans/server/TranslationWorkspaceManagerImpl.java

In both Seam and CDI, the bean's constructor will be invoked twice:
once for the proxy object, and once for the actual instance, so any
logic should be in @Create/@PostConstruct methods, not the constructor.
In Seam, @javax.annotation.PostConstruct methods appear to cause Seam to
treat the bean as an EJB, which means some injections don't happen before
the @PostConstruct method (or at all, possibly).  (These methods will be
migrated to @PostConstruct for CDI.)

Move constructor logic to @Create methods

---

zanata-war/src/main/java/org/zanata/security/SpNegoIdentity.java
zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java

With the move to CDI, using reflection to modify properties on CDI
proxied beans is not recommended. This change addresses said issue when
propagating the Kerberos authentication context onto the Zanata identity
bean.

fix: kerberos ticket-based authentication

---

zanata-war/src/test/java/org/zanata/arquillian/Deployments.java

This was breaking Arquillian test deployments on WildFly, apparently triggered by commit 98016cd142303592a16348007ceee2bd8aced817 (SeamAutowire -> CDI-Unit).

test: exclude unit test inner classes from Arquillian

---

README.md
etc/scripts/quickbuild.sh

Add another script to build zanata.war and document any useful scripts which developers might use to get started or do development with Zanata.

chore: add scripts and docs for common dev tasks

---

pom.xml

This version of DeltaSpike includes an improved windowhandler.js which
preserves #fragments in URLs when a client-side dswid redirect is
triggered. Ref: https://issues.apache.org/jira/browse/DELTASPIKE-1074

Update DeltaSpike to 1.5.4

---

functional-test/src/test/resources/conf/standalone.xml
functional-test/src/test/resources/conf/standalone_wildfly.xml

This should help with liquibase checksum errors for changeset db.changelog-3.1.xml/damason@redhat.com/6 when running functional tests after switching between `release` and `master` branches.

test: back-port document.storage.directory change

---

mkdocs.yml

Remove additional "admin guide" link in the menu
https://zanata.atlassian.net/browse/ZNTA-1107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1172)

doc(admin guide): Move admin guide in the menu

---

docs/release-notes.md
docs/user-guide/system-admin/configuration/infinispan.md
functional-test/src/test/resources/conf/standalone.xml
functional-test/src/test/resources/conf/standalone_wildfly.xml
pom.xml
zanata-overlay/distros/eap-6/standalone/configuration/standalone-zanata.xml
zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml
zanata-war/pom.xml
zanata-war/src/main/java/org/zanata/cache/CacheManagerProducer.java
zanata-war/src/main/resources/ehcache.xml
zanata-war/src/main/resources/zanata-infinispan.xml
zanata-war/src/main/webapp-jboss/WEB-INF/jboss-deployment-structure.xml
zanata-war/src/main/webapp-jboss/WEB-INF/jboss-web.xml
zanata-war/src/test/java/org/zanata/arquillian/Deployments.java
zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
zanata-war/src/test/resources/arquillian/standalone-arquillian.xml

Ideally we would embed Infinispan 8.2 rather than 7.2, but we would have to resolve a number of conflicts in transitive dependency versions (Arquillian-related).
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1183)

ZNTA-1156 Embed Infinispan

---

zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java

TM entity ignored output is logged every time the user moves to
another textflow. The output is for debugging purposes and may
be excessive with large texts and many users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1193)

Set lucene query execution logs to debug

---

zanata-war/src/main/java/org/zanata/adapter/TSAdapter.java
zanata-war/src/main/java/org/zanata/file/SourceDocumentUpload.java

File project document parsing wasn't handling context or comments in any way. This change enables that, and makes use of it for .ts files.
There didn't seem to be a way to get the comment 'part' of a TSFilter TextUnit directly, so an ISkeleton and regex sufficed.
https://zanata.atlassian.net/browse/ZNTA-1132
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1224)

fix(ZNTA-1132): Handle context and comment in Qt ts

---

zanata-war/pom.xml

Without this bridge module, the ocpsoft code seems to use JDK logging, which doesn't seem to behave as expected in the JBoss/WildFly environment (eg ERRORs are reported as SEVERE).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1206)

Enable ocpsoft-rewrite to bridge to JBoss Logging

---

zanata-war/pom.xml
zanata-war/src/test/resources/arquillian.xml

1. Install WildFly somewhere, eg /path/to/wildfly-10.0.0.Final.
This is your ${jboss.home}.
2. Copy standalone-arquillian-wildfly.xml to
${jboss.home}/standalone/configuration/standalone-arquillian.xml
3. Create a launch profile for desired ITCase class
4. Set VM options:
-Djboss.home=/path/to/wildfly-10.0.0.Final # Use your ${jboss.home}
-Darquillian.launch=wildfly # Optional: wildfly container is default
5. IntelliJ IDEA only: make sure working dir is $MODULE_DIR$
6. Run the launch profile.
Not currently working:
- EAP
- Debugging of the wildfly process
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1257)

Enable IDE to run Arquillian tests

---

docs/user-guide/system-admin/configuration/installation.md
zanata-overlay/common/standalone/configuration/zanata.properties

Change the zanata.properties and documentation, in order to provide an working zanata installation instruction for overlay users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1202)

fix(ZNTA-1169): Use different default username and password

---

pom.xml

animal-sniffer-maven-plugin 1.15 expects animal.sniffer.signature to include the full GAV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1264)

Re-enable sniffer for Java 1.8

---

pom.xml
zanata-war/pom.xml

This will allow us to remove .java files from zanata-common-api.jar, which is causing problems for Enunciate 2.
See also https://github.com/zanata/zanata-api/pull/46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-server/1283)

Get api .java files from 'sources' jar

---

zanata-war/src/main/java/org/zanata/util/UrlUtil.java
zanata-war/src/main/java/org/zanata/webtrans/client/view/GlossaryDetailsView.ui.xml
zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryDetailsView.ui.xml
zanata-war/src/main/java/org/zanata/webtrans/server/rpc/GetGlossaryDetailsHandler.java
zanata-war/src/test/java/org/zanata/util/UrlUtilTest.java

JIRA issue URL: *[paste URL here]*
*[Add a short description of what is changed here.]*
- Code quality
- Testing
---- …

fix(glossary details): update glossary link in details page
